import { Resvg } from '@resvg/resvg-js';
import { ReviewObject, CandidateRankingItem } from '../types/index.js';

export class ChartRenderer {
  /**
   * Generates a sleek, compact Radial Score Gauge PNG image for 1 Resume vs 1 JD
   */
  static generateScoreGaugePNG(review: ReviewObject, jdTitle: string): Buffer {
    const score = review.roleFit.score;
    const verdict = review.roleFit.verdict;
    const skills = review.subscores.skills;
    const exp = review.subscores.experience;
    const kw = review.subscores.keywords;
    const format = review.subscores.formatting;

    // SVG arc calculations (r = 75, circumference = 2 * PI * 75 = 471.24)
    const circum = 2 * Math.PI * 75;
    const strokeOffset = circum - (score / 100) * circum;

    // Color based on verdict
    let strokeColor = '#00a884'; // green
    if (score < 50) strokeColor = '#f87171'; // red
    else if (score < 75) strokeColor = '#fbbf24'; // yellow

    const svg = `
      <svg width="600" height="380" viewBox="0 0 600 380" xmlns="http://www.w3.org/2000/svg">
        <rect width="600" height="380" rx="16" fill="#121b22"/>
        
        <!-- Header -->
        <text x="32" y="42" fill="#8696a0" font-family="-apple-system, sans-serif" font-size="13" font-weight="600" letter-spacing="1">ROLEFIT ATS SCORE REPORT</text>
        <text x="32" y="70" fill="#e9edef" font-family="-apple-system, sans-serif" font-size="18" font-weight="700">${this.escapeXml(review.candidateName)} vs ${this.escapeXml(jdTitle.slice(0, 30))}</text>
        <line x1="32" y1="88" x2="568" y2="88" stroke="#2a3942" stroke-width="1"/>

        <!-- Left: Radial Gauge -->
        <g transform="translate(130, 230)">
          <!-- Background track -->
          <circle cx="0" cy="0" r="75" fill="none" stroke="#222e35" stroke-width="14"/>
          <!-- Active fill -->
          <circle cx="0" cy="0" r="75" fill="none" stroke="${strokeColor}" stroke-width="14"
            stroke-dasharray="${circum.toFixed(1)}" stroke-dashoffset="${strokeOffset.toFixed(1)}"
            stroke-linecap="round" transform="rotate(-90)"/>
          
          <text x="0" y="8" text-anchor="middle" fill="#ffffff" font-family="-apple-system, sans-serif" font-size="38" font-weight="800">${score}%</text>
          <text x="0" y="32" text-anchor="middle" fill="#8696a0" font-family="-apple-system, sans-serif" font-size="13" font-weight="600">${this.escapeXml(verdict.toUpperCase())}</text>
        </g>

        <!-- Right: Parameter Breakdown Bars -->
        <g transform="translate(280, 115)">
          <text x="0" y="20" fill="#8696a0" font-family="-apple-system, sans-serif" font-size="12" font-weight="600" letter-spacing="0.5">MATCH PARAMETERS</text>
          
          <!-- Skills Bar -->
          <text x="0" y="52" fill="#e9edef" font-family="-apple-system, sans-serif" font-size="13">Skills Alignment</text>
          <text x="270" y="52" text-anchor="end" fill="#00a884" font-family="-apple-system, sans-serif" font-size="13" font-weight="700">${skills}%</text>
          <rect x="0" y="60" width="270" height="6" rx="3" fill="#222e35"/>
          <rect x="0" y="60" width="${Math.round(270 * (skills / 100))}" height="6" rx="3" fill="#00a884"/>

          <!-- Experience Bar -->
          <text x="0" y="92" fill="#e9edef" font-family="-apple-system, sans-serif" font-size="13">Experience Match</text>
          <text x="270" y="92" text-anchor="end" fill="#53bdeb" font-family="-apple-system, sans-serif" font-size="13" font-weight="700">${exp}%</text>
          <rect x="0" y="100" width="270" height="6" rx="3" fill="#222e35"/>
          <rect x="0" y="100" width="${Math.round(270 * (exp / 100))}" height="6" rx="3" fill="#53bdeb"/>

          <!-- Keywords Bar -->
          <text x="0" y="132" fill="#e9edef" font-family="-apple-system, sans-serif" font-size="13">Keyword Evidence</text>
          <text x="270" y="132" text-anchor="end" fill="#a855f7" font-family="-apple-system, sans-serif" font-size="13" font-weight="700">${kw}%</text>
          <rect x="0" y="140" width="270" height="6" rx="3" fill="#222e35"/>
          <rect x="0" y="140" width="${Math.round(270 * (kw / 100))}" height="6" rx="3" fill="#a855f7"/>

          <!-- ATS Formatting Bar -->
          <text x="0" y="172" fill="#e9edef" font-family="-apple-system, sans-serif" font-size="13">ATS Parseability</text>
          <text x="270" y="172" text-anchor="end" fill="#34d399" font-family="-apple-system, sans-serif" font-size="13" font-weight="700">${format}%</text>
          <rect x="0" y="180" width="270" height="6" rx="3" fill="#222e35"/>
          <rect x="0" y="180" width="${Math.round(270 * (format / 100))}" height="6" rx="3" fill="#34d399"/>
        </g>

        <!-- Footer watermark -->
        <text x="32" y="356" fill="#667781" font-family="-apple-system, sans-serif" font-size="11">Generated by RoleFit AI · Truth-First Resume Review</text>
      </svg>
    `;

    const resvg = new Resvg(svg, { fitTo: { mode: 'width', value: 600 } });
    return resvg.render().asPng();
  }

  /**
   * Generates a Bar Chart PNG comparing N Resumes vs 1 JD
   */
  static generateComparisonBarChartPNG(rankings: CandidateRankingItem[], jdTitle: string): Buffer {
    const height = Math.max(340, 140 + rankings.length * 54);
    const maxBarWidth = 340;

    const barsSvg = rankings.map((c, i) => {
      const y = 130 + i * 54;
      const barWidth = Math.max(10, Math.round(maxBarWidth * (c.score / 100)));
      const medal = i === 0 ? '1' : i === 1 ? '2' : i === 2 ? '3' : `${i + 1}`;
      const medalColor = i === 0 ? '#fbbf24' : i === 1 ? '#94a3b8' : i === 2 ? '#d97706' : '#64748b';
      const barColor = i === 0 ? '#00a884' : c.score >= 70 ? '#53bdeb' : '#f59e0b';

      return `
        <g transform="translate(32, ${y})">
          <!-- Rank Circle -->
          <circle cx="14" cy="14" r="12" fill="${medalColor}"/>
          <text x="14" y="18" text-anchor="middle" fill="#121b22" font-family="-apple-system, sans-serif" font-size="12" font-weight="800">#${medal}</text>

          <!-- Candidate Name -->
          <text x="36" y="18" fill="#e9edef" font-family="-apple-system, sans-serif" font-size="14" font-weight="600">${this.escapeXml(c.candidateName.slice(0, 18))}</text>
          
          <!-- Bar Track & Fill -->
          <rect x="180" y="6" width="${maxBarWidth}" height="18" rx="4" fill="#222e35"/>
          <rect x="180" y="6" width="${barWidth}" height="18" rx="4" fill="${barColor}"/>
          
          <!-- Score Text -->
          <text x="${190 + barWidth}" y="20" fill="#e9edef" font-family="-apple-system, sans-serif" font-size="13" font-weight="700">${c.score}%</text>
        </g>
      `;
    }).join('');

    const svg = `
      <svg width="600" height="${height}" viewBox="0 0 600 ${height}" xmlns="http://www.w3.org/2000/svg">
        <rect width="600" height="${height}" rx="16" fill="#121b22"/>
        
        <!-- Header -->
        <text x="32" y="42" fill="#8696a0" font-family="-apple-system, sans-serif" font-size="13" font-weight="600" letter-spacing="1">CANDIDATE RANKING COMPARISON</text>
        <text x="32" y="70" fill="#e9edef" font-family="-apple-system, sans-serif" font-size="18" font-weight="700">${this.escapeXml(jdTitle.slice(0, 36))}</text>
        <line x1="32" y1="88" x2="568" y2="88" stroke="#2a3942" stroke-width="1"/>

        <!-- Candidate Bars -->
        ${barsSvg}

        <!-- Footer -->
        <text x="32" y="${height - 20}" fill="#667781" font-family="-apple-system, sans-serif" font-size="11">Generated by RoleFit AI · Fair Multi-Candidate Ranking</text>
      </svg>
    `;

    const resvg = new Resvg(svg, { fitTo: { mode: 'width', value: 600 } });
    return resvg.render().asPng();
  }

  private static escapeXml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  }
}
